config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homes#top'
  resources :users, only: %i[index show edit update] do
    resource :relationships, only: %i[create destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  post 'users/search', to: 'users#search'

  resources :fashions, only: %i[new create index show edit update destroy] do
    resource :favorites, only: %i[create destroy]
    resources :fashion_comments, only: %i[create destroy]
  end

  post 'fashions/search', to: 'fashions#search'

  post 'follow/:id' => 'relationships#follow', as: 'follow'
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'

  resources :relationships, only: %i[create destroy]

  post 'search', to: 'application#search'
end

app/models/user.rb
class User < ApplicationRecord
  attachment :image
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :fashions, dependent: :destroy
  has_many :fashion_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :follower, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :followed, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower

  validates :name, presence: true, length: { in: 2..20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    following_user.include?(user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.all
    @fashions = Fashion.all
    @fashion = Fashion.new
  end

  def show
    @user = User.find(params[:id])
    @fashion = Fashion.new
    @fashions = @user.fashions
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render :edit
    else
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = 'fashion was successfully updated.'
      redirect_to user_path(current_user.id)
    else
      render :edit
    end
  end

  def search
    redirect_to users_path if params[:keyword] == ''

    split_keyword = params[:keyword].split(/[[:blank:]]+/)

    users = []
    split_keyword.each do |keyword|  # 分割したキーワードごとに検索
      next if keyword == ''

      users << User.where('name LIKE(?)', "%#{keyword}%").pluck('id') # 部分一致で検索
    end

    # @user = User.all
    @user = User.where(id: users.flatten).page(params[:page]).reverse_order.per(9)
    @fashions = Fashion.all
    @fashion = Fashion.new

    render action: :index
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :image)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<main class="container">
  <h2 class="py-5"></h2>
  <%= form_with model:@user, local:true do |f| %>
    <div class="py-3 text-center">
      <label for="inputName">Name</label>
      <%= f.text_field :name, autofocus: true %>
    </div>
    <div class="py-3 text-center">
      <label for="inputImage">Image</label>
      <%= f.attachment_field :image, autofocus: true %>
    </div>
    <div class="py-3 text-center">
      <label for="inputIntroduction">Introduction</label>
      <%= f.text_field :introduction, autofocus: true %>
    </div>
    <div class="py-3 text-center">
      <%= f.submit "Update User" %>
    </div>
  <% end %>

  <%if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this fashion from being saved:</h2>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
    </div>
  <% end %>
</main>

app/views/users/index.html.erb
<main class="container">
  <div class="mt-3">
    <%= form_tag('/users/search', method: :post) do %>
       <input id="page_name" name='keyword' size="20" type="text" />
     　<%= submit_tag "search" %>
  　<% end %>
  </div>
  <div class="row">
    <%if @fashion.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@fashion.errors.count, "error") %> prohibited this fashion from being saved:</h2>
          <ul>
            <% @fashion.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
      </div>
    <% end %>
  <div class="col-md-10 offset-md-1">
    <div class="py-5">
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th>follow</th>
            <th>follower</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @user.each do |user| %>
            <tr>
              <td>
                <%= link_to user_path(user.id) do %>
                  <div class="img">
                  <%= attachment_image_tag user, :image, fallback: "no_image.png", size: "40x40", class: "user_profile_image" %>
                </div>
                <% end %>
              </td>
              <td>
                <%= user.name %>
              </td>
              <td>
                <p><%= user.follower.count %></p>
              </td>
              <td>
                <p><%= user.followed.count %></p>
              </td>
              <td>
                <% if current_user.following?(user) %>
                  <%= link_to 'unfollow', unfollow_path(user.id), method: :POST, class: 'btn btn-light' %>
                <% else %>
                  <%= link_to 'follow', follow_path(user.id), method: :POST, class: 'btn btn-light' %>
                <% end %>
              </td>
              <td>
                <%= link_to "Show", user_path(user.id), class: 'btn btn-light' %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<main class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1">
      <div class="py-5">
        <table class="table">
          <tbody>
            <tr>
              <th>
                <div class="img">
                  <%= attachment_image_tag @user, :image, :fill, 100, 100, fallback: "no_image.png", class: "user_profile_image" %>
                </div>
              </th>
              <th>
                <p>follow</p>
                <p><%= @user.follower.count %></p>
              </th>
              <th>
                <p>follower</p>
                <p><%= @user.followed.count %></p>
              </th>
            </tr>
            <tr>
          	  <th>name</th>
          	  <th><%= @user.name %></th>
            </tr>
            <tr>
          	  <th>introduction</th>
          	  <th><%= @user.introduction %></th>
            </tr>
          </tbody>
        </table>
        <%= link_to edit_user_path(current_user), class: 'btn btn-light' do %>
          <i class="fas fa-user-cog"></i>
        <% end %>
      </div>
    </div>

    <%if @fashion.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@fashion.errors.count, "error") %> prohibited this fashion from being saved:</h2>
          <ul>
            <% @fashion.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
      </div>
    <% end %>
          <% @fashions.each do |fashion| %>
            <div class="col-sm-3 offset-md-1">
              <p class="post_image">
                <% fashion.fashion_images.each do |fashion_image| %>
                  <%= link_to fashion_path(fashion.id) do %>
                    <%= attachment_image_tag fashion_image, :image, :fill, 200, 200, fallback: "no_image.png" %>
                  <% end %>
                <% end %>
              </p>
              <p>
                <%= fashion.introduction %>
              </p>
              <div class="dropdown">
                <a class="btn btn-light dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></a>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                  <a class="dropdown-item" href="#"><%= link_to "Edit", edit_fashion_path(fashion.id), class: 'btn btn-light' %></a>
                  <a class="dropdown-item" href="#"><%= link_to "Destroy", fashion_path(fashion.id), class: 'btn btn-light', method: :delete, "data-confirm" => "本当に削除しますか？" %></a>
                </div>
              </div>
            </div>
          <% end %>
      </div>
  </div>
</main>