config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homes#top'
  resources :users, only: %i[index show edit update] do
    resource :relationships, only: %i[create destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  post 'users/search', to: 'users#search'

  resources :fashions, only: %i[new create index show edit update destroy] do
    resource :favorites, only: %i[create destroy]
    resources :fashion_comments, only: %i[create destroy]
  end

  post 'fashions/search', to: 'fashions#search'

  post 'follow/:id' => 'relationships#follow', as: 'follow'
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'

  resources :relationships, only: %i[create destroy]

  post 'search', to: 'application#search'
end

app/models/fashion.rb
class Fashion < ApplicationRecord
  belongs_to :user
  has_many :fashion_images, dependent: :destroy
  accepts_attachments_for :fashion_images, attachment: :image
  has_many :fashion_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :tag_maps, dependent: :destroy
  has_many :tags, through: :tag_maps

  validates :introduction, presence: true
  validate :discount_cannot_be_greater_than_total_value

  def discount_cannot_be_greater_than_total_value
    if fashion_images.size == 0
      # errors.add(:base, "There is not an image")
    end
  end

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def save_tag(sent_tags)
    current_tags = tags.pluck(:tag_name) unless tags.nil?
    old_tags = current_tags - sent_tags
    new_tags = sent_tags - current_tags

    old_tags.each do |old|
      tags.delete Tag.find_by(tag_name: old)
    end

    new_tags.each do |new|
      new_tag = Tag.find_or_create_by(tag_name: new)
      tags << new_tag
    end
  end
end

app/controllers/fashions_controller.rb
class FashionsController < ApplicationController
  def new
    @fashion = Fashion.new
  end

  def create
    @fashion = Fashion.new(fashion_params)
    tag_list = params[:fashion][:tag_name].split(nil)
    @fashion.user = current_user
    if @fashion.save
      @fashion.save_tag(tag_list)
      flash[:notice] = 'You have created fashion successfully.'
      redirect_to user_path(current_user.id)
    else
      render :new
    end
  end

  def index
    @tag_list = Tag.all
    @fashion = Fashion.new
    @fashions = Fashion.page(params[:page]).reverse_order.per(9)
    @user = User.all
  end

  def show
    @fashion = Fashion.find(params[:id])
    @fashion_new = Fashion.new
    @fashion_comment = FashionComment.new
    @fashion_tags = @fashion.tags
  end

  def edit
    @fashion = Fashion.find(params[:id])
    @fashion.fashion_images.build
    if @fashion.user == current_user
      render :edit
    else
      redirect_to fashions_path
    end
  end

  def update
    @fashion = Fashion.find(params[:id])
    tag_list = params[:fashion][:tag_name].split(nil)
    if @fashion.update(fashion_params)
      @fashion.save_tag(tag_list)
      flash[:notice] = 'fashion was successfully updated.'
      redirect_to user_path(current_user.id)
    else
      render :edit
    end
  end

  def destroy
    @fashion = Fashion.find(params[:id])
    @fashion.destroy
    redirect_to user_path(current_user.id)
  end

  def search
    redirect_to fashions_path if params[:keyword] == ''

    split_keyword = params[:keyword].split(/[[:blank:]]+/)

    fashions = []
    split_keyword.each do |keyword|  # 分割したキーワードごとに検索
      next if keyword == ''

      fashions << Fashion.where('introduction LIKE(?)', "%#{keyword}%").pluck('id') # 部分一致で検索
    end

    @tag_list = Tag.all
    @fashion = Fashion.new
    @fashions = Fashion.where(id: fashions.flatten).page(params[:page]).reverse_order.per(9)
    @user = User.all

    render action: :index
  end

  private

  def fashion_params
    params.require(:fashion).permit(:introduction, fashion_images_images: [])
  end
end

app/helpers/fashions_helper.rb
module FashionsHelper
end

app/views/fashions/edit.html.erb
<main class="container">
  <%= flash[:notice] %>
<h2 class="py-5"></h2>
  <div class="py-5 text-center">
    <%= form_with model:@fashion, local:true do |f| %>
      <% if @fashion.fashion_images.present? %>
        <% @fashion.fashion_images.each do |image| %>
          <%= attachment_image_tag image, :image, class: "default_image" %>
        <% end %>
      <% end %>
      <%= f.attachment_field :fashion_images_images, multiple: true %>
      <label for="inputIntroduction">Opinion</label>
      <%= f.text_field :introduction, autofocus: true, id:"inputintroduction" %></br>
      <label for="inputTag">Tag</label>
      <% if @fashion.tag_maps.present? %>
        <% @fashion.tags.each do |tag| %>
          <%= f.text_field :tag_name, autofocus: true, id:"tag_name" %>
        <% end %>
      <% end %>
      <%= f.submit "Update" %>
    <% end %>
  </div>

  <div class="py-3 text-center">
    <%= link_to "Show", fashion_path(@fashion.id), class: 'btn btn-default' %>
    <%= link_to "Back", user_path(@fashion.user.id), class: 'btn btn-default' %>
  </div>

  <%if @fashion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fashion.errors.count, "error") %> prohibited this fashion from being saved:</h2>
        <ul>
          <% @fashion.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
    </div>
  <% end %>
  </main>

app/views/fashions/index.html.erb
<main class="container">
  <div class="mt-4">
   <%= form_tag('/fashions/search', method: :post) do %>
     　<input id="page_name" name='keyword' size="20" type="text" />
     　<%= submit_tag "search" %>
  　<% end %>
  </div>
  <div class="row">
    <%= flash[:notice] %>
      <%if @fashion.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@fashion.errors.count, "error") %> prohibited this fashion from being saved:</h2>
            <ul>
             <% @fashion.errors.full_messages.each do |message| %>
               <li><%= message %></li>
             <% end %>
            </ul>
        </div>
      <% end %>
      <% @fashions.each do |fashion| %>
        <div class="col-sm-3 offset-md-1">
          <div class="py-5"></div>
             <p class="post_image">
              <% fashion.fashion_images.each do |fashion_image| %>
                <%= link_to fashion_path(fashion.id) do %>
                  <%= attachment_image_tag fashion_image, :image, :fill, 250, 250, fallback: "no_image.png" %>
                <% end %>
              <% end %>
            </p>
            <div id=<%="likes_buttons_#{fashion.id}"%>>
               <% if fashion.favorited_by?(current_user) %>
                  <p>
                    <%= link_to fashion_favorites_path(fashion.id), method: :delete, remote: true do %>
                      ♥<%= fashion.favorites.count %>
                    <% end %>
                  </p>
                  <% else %>
                  <p>
                    <%= link_to fashion_favorites_path(fashion.id), method: :post, remote: true do %>
                      ♡<%= fashion.favorites.count %>
                    <% end %>
                  </p>
                <% end %>
            </div>
            <p>
              <%= fashion.introduction %></p>
            <div class="dropdown">
              <a class="btn btn-light dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></a>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                <a class="dropdown-item" href="#"><%= link_to fashion_path(fashion.id), class: 'btn btn-light' do %><%= fashion.fashion_comments.count %> comment <% end %></a>
                <a class="dropdown-item" href="#"><%= link_to "Show", fashion_path(fashion.id), class: 'btn btn-light' %></a>
              </div>
            </div>
        </div>
      <% end %>
    </div>
  <%= paginate @fashions %>
</main>

app/views/fashions/new.html.erb
<h2 class="py-5 text-center">New Post</h2>
<%= form_with model: @fashion, local:true do |f| %>
  <div class="mt-3 text-center form-group">
    <label for="fashion_image">Image</label>
  </div>
  <div class="pb-3 text-center form-group">
    <%= f.attachment_field :fashion_images_images, multiple: true %>
  </div>
  <div class="mt-3 text-center form-group">
    <label for="fashion_opinion">Opinion</label>
  </div>
  <div class="pb-3 text-center form-group">
    <%= f.text_area :introduction %>
  </div>
  <div class="mt-3 text-center form-group">
    <label for="fashion_opinion">Tag</label>
  </div>
  <div class="pb-3 text-center form-group">
    <%= f.text_field :tag_name %>
  </div>
  <div class="py-3 text-center form-group">
    <%= f.submit 'submit' %>
  </div>
<% end %>
<%if @fashion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fashion.errors.count, "error") %> prohibited this fashion from being saved:</h2>
        <ul>
          <% @fashion.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
    </div>
<% end %>

app/views/fashions/show.html.erb
<main class="container">
  <%if @fashion_new.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fashion_new.errors.count, "error") %> prohibited this fashion from being saved:</h2>
        <ul>
          <% @fashion_new.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
    </div>
  <% end %>
  <div class="col-md-10 offset-md-1">
    <div class="py-3"></div>
    <div class="py-4 text-center">
      <% @fashion.fashion_images.each do |fashion_image| %>
        <%= attachment_image_tag fashion_image, :image, :fill, 200, 200, fallback: "no_image.png" %>
      <% end %>
    </div>
    <table class="table table-hover table-inverse">
      <tmain>
        <tr>
          <td>
            <%= link_to user_path(@fashion.user.id) do %>
              <%= attachment_image_tag @fashion.user, :image, fallback: "no_image.png", size: "40x40" %>
              <%= @fashion.user.name %>
            <% end %>
          </td>
          <td id=<%="likes_buttons_#{@fashion.id}"%>>
             <% if @fashion.favorited_by?(current_user) %>
                <p>
                  <%= link_to fashion_favorites_path(@fashion), method: :delete, remote: true do %>
                    ♥<%= @fashion.favorites.count %>
                  <% end %>
                </p>
                <% else %>
                <p>
                  <%= link_to fashion_favorites_path(@fashion), method: :post, remote: true do %>
                    ♡<%= @fashion.favorites.count %>
                  <% end %>
                </p>
              <% end %>
          </td>
          <td>
            <%=@fashion.introduction %>
          </td>
          <td>
            <% @fashion.tags.each do |tag| %>
            <ul class="tag-list">
              <li class="tag-style">#<%= tag.tag_name %></li>
            </ul>
          <% end %>
          </td>
          <td>
            <p>comment：<%= @fashion.fashion_comments.count %></p>
          </td>
        </tr>
    </table>
    <div class="comments">
      <% @fashion.fashion_comments.each do |fashion_comment| %>
        <%= link_to user_path(fashion_comment.user.id) do %>
          <%= attachment_image_tag fashion_comment.user, :image, fallback: "no_image.png", size: "40x40" %>
          <%= @fashion.user.name %>
        <% end %>
        <%= fashion_comment.comment %>
        <% if fashion_comment.user == current_user %>
          <div class="comment-delete">
            <%= link_to "Destroy", fashion_fashion_comment_path(fashion_comment.fashion, fashion_comment), method: :delete %>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="new-comment">
      <%= form_with(model:[@fashion, @fashion_comment], local: true) do |f| %>
        <%= f.text_area :comment, rows:'5', size: "90x5", required: true %><br />
        <%= f.submit "submit" %>
      <% end %>
    </div>
  </div>
</main>