config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homes#top'
  resources :users, only: %i[index show edit update] do
    resource :relationships, only: %i[create destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  post 'users/search', to: 'users#search'

  resources :fashions, only: %i[new create index show edit update destroy] do
    resource :favorites, only: %i[create destroy]
    resources :fashion_comments, only: %i[create destroy]
  end

  post 'fashions/search', to: 'fashions#search'

  post 'follow/:id' => 'relationships#follow', as: 'follow'
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'

  resources :relationships, only: %i[create destroy]

  post 'search', to: 'application#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fashion.rb
class Fashion < ApplicationRecord
  belongs_to :user
  has_many :fashion_images, dependent: :destroy
  accepts_attachments_for :fashion_images, attachment: :image
  has_many :fashion_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :tag_maps, dependent: :destroy
  has_many :tags, through: :tag_maps

  validates :introduction, presence: true
  validate :discount_cannot_be_greater_than_total_value

  def discount_cannot_be_greater_than_total_value
    if fashion_images.size == 0
      # errors.add(:base, "There is not an image")
    end
  end

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def save_tag(sent_tags)
    current_tags = tags.pluck(:tag_name) unless tags.nil?
    old_tags = current_tags - sent_tags
    new_tags = sent_tags - current_tags

    old_tags.each do |old|
      tags.delete Tag.find_by(tag_name: old)
    end

    new_tags.each do |new|
      new_tag = Tag.find_or_create_by(tag_name: new)
      tags << new_tag
    end
  end
end

app/models/fashion_comment.rb
class FashionComment < ApplicationRecord
  belongs_to :user
  belongs_to :fashion

  validates :comment, presence: true
end

app/models/fashion_image.rb
class FashionImage < ApplicationRecord
  belongs_to :fashion
  attachment :image
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :fashion
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tag_maps, dependent: :destroy, foreign_key: 'tag_id'
  has_many :fashions, through: :tag_maps
end

app/models/tag_map.rb
class TagMap < ApplicationRecord
  belongs_to :fashion
  belongs_to :tag

  validates :fashion_id, presence: true
  validates :tag_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  attachment :image
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :fashions, dependent: :destroy
  has_many :fashion_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :follower, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :followed, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower

  validates :name, presence: true, length: { in: 2..20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    following_user.include?(user)
  end
end

app/controllers/fashions_controller.rb
class FashionsController < ApplicationController
  def new
    @fashion = Fashion.new
  end

  def create
    @fashion = Fashion.new(fashion_params)
    tag_list = params[:fashion][:tag_name].split(nil)
    @fashion.user = current_user
    if @fashion.save
      @fashion.save_tag(tag_list)
      flash[:notice] = 'You have created fashion successfully.'
      redirect_to user_path(current_user.id)
    else
      render :new
    end
  end

  def index
    @tag_list = Tag.all
    @fashion = Fashion.new
    @fashions = Fashion.page(params[:page]).reverse_order.per(9)
    @user = User.all
  end

  def show
    @fashion = Fashion.find(params[:id])
    @fashion_new = Fashion.new
    @fashion_comment = FashionComment.new
    @fashion_tags = @fashion.tags
  end

  def edit
    @fashion = Fashion.find(params[:id])
    @fashion.fashion_images.build
    if @fashion.user == current_user
      render :edit
    else
      redirect_to fashions_path
    end
  end

  def update
    @fashion = Fashion.find(params[:id])
    tag_list = params[:fashion][:tag_name].split(nil)
    if @fashion.update(fashion_params)
      @fashion.save_tag(tag_list)
      flash[:notice] = 'fashion was successfully updated.'
      redirect_to user_path(current_user.id)
    else
      render :edit
    end
  end

  def destroy
    @fashion = Fashion.find(params[:id])
    @fashion.destroy
    redirect_to user_path(current_user.id)
  end

  def search
    redirect_to fashions_path if params[:keyword] == ''

    split_keyword = params[:keyword].split(/[[:blank:]]+/)

    fashions = []
    split_keyword.each do |keyword|  # 分割したキーワードごとに検索
      next if keyword == ''

      fashions << Fashion.where('introduction LIKE(?)', "%#{keyword}%").pluck('id') # 部分一致で検索
    end

    @tag_list = Tag.all
    @fashion = Fashion.new
    @fashions = Fashion.where(id: fashions.flatten).page(params[:page]).reverse_order.per(9)
    @user = User.all

    render action: :index
  end

  private

  def fashion_params
    params.require(:fashion).permit(:introduction, fashion_images_images: [])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @fashion = Fashion.find(params[:fashion_id])
    favorite = current_user.favorites.new(fashion_id: @fashion.id)
    favorite.save
  end

  def destroy
    @fashion = Fashion.find(params[:fashion_id])
    favorite = current_user.favorites.find_by(fashion_id: @fashion.id)
    favorite.destroy
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.all
    @fashions = Fashion.all
    @fashion = Fashion.new
  end

  def show
    @user = User.find(params[:id])
    @fashion = Fashion.new
    @fashions = @user.fashions
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render :edit
    else
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = 'fashion was successfully updated.'
      redirect_to user_path(current_user.id)
    else
      render :edit
    end
  end

  def search
    redirect_to users_path if params[:keyword] == ''

    split_keyword = params[:keyword].split(/[[:blank:]]+/)

    users = []
    split_keyword.each do |keyword|  # 分割したキーワードごとに検索
      next if keyword == ''

      users << User.where('name LIKE(?)', "%#{keyword}%").pluck('id') # 部分一致で検索
    end

    # @user = User.all
    @user = User.where(id: users.flatten).page(params[:page]).reverse_order.per(9)
    @fashions = Fashion.all
    @fashion = Fashion.new

    render action: :index
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fashion_comments_helper.rb
module FashionCommentsHelper
end

app/helpers/fashions_helper.rb
module FashionsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fashion Show</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <h3>Fashion Show</h3>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= form_tag(search_path, method: :post)  do %>
                  <%= select_tag "tag", options_from_collection_for_select(Tag.all, "id", "tag_name"), include_blank: true %>
                  <%= submit_tag 'search'%>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to new_fashion_path, class: 'nav-link text-dark' do %>
                  <i class="fas fa-angle-double-right">NewPost</i>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to user_path(current_user.id), class: 'nav-link text-dark' do %>
                  <i class="fas fa-user">MyPages</i>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to users_path, class: 'nav-link text-dark' do %>
                  <i class="fas fa-users">Users</i>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to fashions_path, class: 'nav-link text-dark' do %>
                  <i class="fas fa-tshirt">Fashions</i>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-dark' do %>
                  <i class="fas fa-sign-out-alt">Logout</i>
                <% end %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to "Home", root_path, class: 'fas fa-home nav-link text-dark' %>
              </li>
              <li class="nav-item">
                <%= link_to "Sign up", new_user_registration_path, class: 'fas fa-user-plus nav-link text-dark' %>
              </li>
              <li class="nav-item">
                <%= link_to "Login", new_user_session_path, class: 'fas fa-sign-in-alt nav-link text-dark' %>
              </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <%= flash[:notice] %>
    <main class="mb-auto">
    <%= yield %>
    </main>
    <footer>
      <div class="py-5 text-center">
        <ul class="p-0 list-unstyled">
          <li>
            <a href="" title="" class="text-black-50">CopyRight FashionShow.inc</a>
          </li>
        </ul>
      </div>
    </footer>
  </body>
</html>